### ISSUE TITLE
Resource names too long

### ISSUE THREAD

**Issue by flogy** [thefinnomenon/graphql-algolia-transformer#7]
Hi @thefinnomenon ,

First of all, thanks for this awesome transformer!

I recently had the issue that the generated resource names for the lambda function and the IAM role were too long (exceeding the maximum of 64 characters). To fix it I did overwrite the default values of `AlgoliaLambdaFunctionName` and `AlgoliaLambdaIAMRoleName`.

However, I think it would be nice to shorter names by default. A possibility would be to not join the GraphQL API ID anymore (e.g. [here](https://github.com/thefinnomenon/graphql-algolia-transformer/blob/7a6d0ca297921b95483f5e84c254b7d6c4ee8884/src/resources.ts#L239)). Or is there a specific reason the ID is included in the function / IAM role names?

Thanks in advance.

**Comment by noyfactor** [comment]
+1 on that, also getting the lambda function name too long. This should probably be configurable from the directive itself, or from `parameters.json`  as a template

**Comment by thefinnomenon** [comment]
I removed the ID from the names and added the ability to configure them from the directive (thanks @noyfactor for the suggestion!)

@flogy I had added the ID in order to guarantee uniqueness between functions (e.g. you have two different projects with a searchable Post table).

I'm going to close this issue as the newest release should fix it. Please re-open it if you still have the issue.
